### ISSUE TITLE
您好，请问数据的怎么读取的？可以提供下读取数据的代码吗

### ISSUE THREAD

**Issue by dreamitposssiable** [Yaziwel/Region-Attention-Transformer-for-Medical-Image-Restoration#4]
您好，我是一名刚接触这个方向的学生，请问图像数据和mask是怎么批量处理的？通过SAM得到了一个图片的对应mask，但是在使用RAT时需要批量数据，于是我把图像重新批量输入，改了通道顺序变成bchw，但报错显示RAT的output高为0。数据集和mask具体是怎样批量输入的呢？图像数据的float类型是设置成32位还是64位比较好？感激不尽，期待您的回复。

**Comment by Yaziwel** [comment]
> 您好，我是一名刚接触这个方向的学生，请问图像数据和mask是怎么批量处理的？通过SAM得到了一个图片的对应mask，但是在使用RAT时需要批量数据，于是我把图像重新批量输入，改了通道顺序变成bchw，但报错显示RAT的output高为0。数据集和mask具体是怎样批量输入的呢？图像数据的float类型是设置成32位还是64位比较好？感激不尽，期待您的回复。

模型的输入LR图的shape是[B,C,H,W]，输入mask的shape是[B,H,W]。mask的示例见[example_img](https://github.com/Yaziwel/Region-Attention-Transformer-for-Medical-Image-Restoration/tree/main/example_img)。图像用float 32就行

**Comment by dreamitposssiable** [comment]
好的，谢谢，非常感谢您的解答
